name: Build and Push Docker

on:
  push:
    branches: [main]
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Set up Java 21
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      # 3. Increment patch version
      - name: Increment patch version
        run: |
          mvn build-helper:parse-version versions:set \
            -DnewVersion="\${parsedVersion.majorVersion}.\${parsedVersion.minorVersion}.\$((\${parsedVersion.incrementalVersion}+1))" \
            versions:commit

      # 4. Get new version
      - name: Get new version
        id: get_version
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "New version: $VERSION"

      # 5. Build Maven package
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      # 6. Build Docker image
      - name: Build Docker image
        run: docker build -t byakuka/simple-java-app:$VERSION .

      # 7. Login to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 8. Push Docker image
      - name: Push Docker image
        run: docker push byakuka/simple-java-app:$VERSION

