name: Build and Push Docker

on:
  push:
    branches: [main]
  workflow_dispatch:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Set up Java 21
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      # 3. Cache Maven packages
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # 4. Increment patch version
      - name: Increment patch version
        run: |
          CURRENT_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "Current version: $CURRENT_VERSION"

          IFS='.' read -r MAJOR MINOR PATCH <<< "$CURRENT_VERSION"
          PATCH=$((PATCH+1))
          NEW_VERSION="$MAJOR.$MINOR.$PATCH"
          echo "New version: $NEW_VERSION"

          # Update pom.xml
          mvn versions:set -DnewVersion=$NEW_VERSION -DgenerateBackupPoms=false

          # Commit updated pom.xml so it's saved in the branch
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add pom.xml
          git commit -m "Increment patch version to $NEW_VERSION" || echo "No changes to commit"
          git push origin HEAD:main || echo "Push failed, maybe no permission"

      # 5. Set VERSION env variable
      - name: Set version
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "New version: $VERSION"

      # 6. Build Maven package
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      # 7. Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 8. Login to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 9. Build Docker image
      - name: Build Docker image
        run: docker build -t byakuka/simple-java-app:"$VERSION" .

      # 10. Push Docker image
      - name: Push Docker image
        run: docker push byakuka/simple-java-app:"$VERSION"
