name: Build and Push Docker

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Get current version
        id: get_version
        run: |
          VERSION=$(xmllint --xpath "string(//*[local-name()='project']/*[local-name()='version'])" pom.xml)
          echo "version=$VERSION" >> $GITHUB_ENV

      - name: Increment version
        id: increment_version
        uses: christian-draeger/increment-semantic-version@v1.2.3
        with:
          current-version: ${{ steps.get_version.outputs.version }}
          version-fragment: patch

      - name: Set new version in pom.xml
        run: |
          mvn versions:set -DnewVersion=${{ steps.increment_version.outputs.next-version }}
          mvn versions:commit

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Build Docker image
        run: docker build -t christina-draeger/simple-java-app:${{ steps.increment_version.outputs.next-version }} .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image
        run: docker push christina-draeger/simple-java-app:${{ steps.increment_version.outputs.next-version }}

